"""Add amount and transfer_acc_id to transaction

Revision ID: 3c3a1c360547
Revises: e29a36f0ad74
Create Date: 2019-10-14 20:57:49.343585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3a1c360547'
down_revision = 'e29a36f0ad74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('amount', sa.Float(), nullable=True))
    #op.add_column('transaction', sa.Column('transfer_account_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'transaction', 'account', ['transfer_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'transfer_account_id')
    op.drop_column('transaction', 'amount')
    # ### end Alembic commands ###
